version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    command: [ "--config.file=/prometheus-config/prometheus.yml" ]
    volumes:
      - ./prometheus/prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    volumes:
      - ./data/grafana:/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  application:
    build: ./gamesApi
    ports:
      - 3333:3333
